name: Rust

on:
  push:
    branches:
    - master
    - develop
    - feature/*
    - bugfix/*
    - hotfix/*
    - release/*
  pull_request:
    branches:
    - master
    - develop
    - feature/*
    - bugfix/*
    - hotfix/*
    - release/*
  schedule:
    - cron: '0 15 * * 5'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

